SEABREEZE = ../../../..

all: deps objs

SUBDIRS = \
    acquisition_delay   \
    continuous_strobe   \
    data_buffer         \
    eeprom_slots        \
    fpga_register       \
    irradcal            \
    light_source        \
    nonlinearity        \
    temperature         \
    revision            \
    optical_bench       \
    raw_bus_access      \
    serial_number       \
    shutter             \
    spectrometer        \
    spectrum_processing \
    stray_light         \
    thermoelectric      \
    wavecal             \
    pixel_binning

include $(SEABREEZE)/common.mk
