SEABREEZE = ../../../..

all: deps objs

SUBDIRS = \
    acquisition_delay   \
    continuous_strobe   \
    data_buffer         \
    eeprom_slots        \
    fpga_register       \
    irradcal            \
    light_source        \
    introspection		\
    nonlinearity        \
    temperature         \
    revision            \
    optical_bench       \
    raw_bus_access      \
    serial_number       \
    shutter             \
    spectrometer        \
    spectrum_processing \
    stray_light         \
    thermoelectric      \
    wavecal             \
    pixel_binning		\
    ethernet_configuration \
    fast_buffer 		\
    ipv4				\
    multicast			\
    network_configuration	\
    wifi_configuration	\
    dhcp_server \
    gpio \
    i2c_master

include $(SEABREEZE)/common.mk
