SEABREEZE = ../../../..

all: deps objs

SUBDIRS = \
    continuous_strobe   \
    eeprom_slots        \
    fpga_register       \
    irradcal            \
    light_source        \
    nonlinearity        \
    raw_bus_access      \
    serial_number       \
    shutter             \
    spectrometer        \
    stray_light         \
    thermoelectric      \
    wavecal

include $(SEABREEZE)/common.mk
